name: Create new release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract version
        run: echo "release_version=$(jq -rj .version info.json)" >> $GITHUB_ENV
      - name: Package zip
        run: |
          rm -rf out
          mkdir out
          cp -r locale changelog.txt control.lua info.json LICENCE out
          zip -r "out/fctrl-observers-mod_${{ env.release_version }}.zip" out
      - name: Create git tag
        uses: actions/github-script@v5
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tag/${{ env.release_version }}",
              sha: context.sha
            })
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.release_version }}
          files: |
            out/fctrl-observers-mod_${{ env.release_version }}.zip
